service: foray-watch-serverless

useDotenv: true

plugins:
  - serverless-plugin-reducer

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  #region doesn't matter as it should be closer to dB
  #also Telegram probably has an endpoint close to there
  region: us-east-1
  memorySize: 128
  timeout: 5
  endpointType: regional

  environment:
    API_TOKEN: ${env:API_TOKEN}
    DATABASE_URL: ${env:DATABASE_URL}
    LOG_GROUP_ID: ${env:LOG_GROUP_ID}
    NODE_ENV: production

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: webhook
          method: post
          cors: true
  set-webhook:
    handler: handler.setWebhook
    events:
      - http:
          path: setWebhook
          method: post
          cors: true
